### ISSUE TITLE
Failed to apply upload policy on writting with com.pinterest.secor.uploader.GsUploadManager

### ISSUE THREAD

**Issue by deividas-smolskas** [pinterest/secor#1168] opened 2020-01-30 22:37 UTC
```
(com.pinterest.secor.consumer.Consumer:186) ERROR Thread failed
java.lang.RuntimeException: Failed to apply upload policy
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:196)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:177)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:36)
	at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:133)
	at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:281)
	at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:320)
	at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:194)
	... 1 more
Caused by: java.lang.NoSuchMethodError: com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J
	at com.google.api.client.http.ConsumingInputStream.close(ConsumingInputStream.java:40)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:252)
	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:369)
	at com.google.api.client.json.jackson2.JacksonParser.close(JacksonParser.java:47)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:365)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:337)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:79)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:73)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:444)
	at com.google.auth.oauth2.ComputeEngineCredentials.refreshAccessToken(ComputeEngineCredentials.java:154)
	at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:157)
	at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:145)
	at com.google.auth.http.HttpCredentialsAdapter.initialize(HttpCredentialsAdapter.java:91)
	at com.google.cloud.http.HttpTransportOptions$1.initialize(HttpTransportOptions.java:159)
	at com.google.cloud.http.CensusHttpModule$CensusHttpRequestInitializer.initialize(CensusHttpModule.java:109)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:88)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:423)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:399)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.open(HttpStorageRpc.java:789)
	at com.google.cloud.storage.BlobWriteChannel$2.call(BlobWriteChannel.java:84)
	at com.google.cloud.storage.BlobWriteChannel$2.call(BlobWriteChannel.java:81)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.BlobWriteChannel.open(BlobWriteChannel.java:80)
	at com.google.cloud.storage.BlobWriteChannel.<init>(BlobWriteChannel.java:35)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:630)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:620)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:84)
	at com.pinterest.secor.uploader.GsUploadManager$1.run(GsUploadManager.java:114)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by HenryCaiHaiying** [comment] 2020-01-31 05:24
Most likely one of the google packages needs to be updated:

Caused by: java.lang.NoSuchMethodError:
com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J

	at com.google.api.client.http.ConsumingInputStream.close(ConsumingInputStream.java:40)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:252)

**Comment by sdomalap** [comment] 2020-03-18 13:45
By default, the Secor package comes with guava version [18.0.](https://github.com/pinterest/secor/blob/master/pom.xml#L317)

But the method [ByteStreams.exhaust](https://guava.dev/releases/20.0/api/docs/com/google/common/io/ByteStreams.html#exhaust-java.io.InputStream-) is only available in versions higher than [20.0.](https://guava.dev/releases/20.0/api/docs/com/google/common/io/ByteStreams.html#exhaust-java.io.InputStream-) We had to change the dependency version to 20.0 and rebuild the package to make it work.

**Comment by HenryCaiHaiying** [comment] 2020-03-18 19:08
Feel free to submit a PR to upgrade guava

**Comment by sdomalap** [comment] 2020-03-18 19:16
Will submit a PR. Thanks

**Comment by sdomalap** [comment] 2020-03-19 14:50
@HenryCaiHaiying submitted a [PR](https://github.com/pinterest/secor/pull/1230)

**Comment by HenryCaiHaiying** [comment] 2020-03-19 18:54
Thanks for the fix, merged in.

**Closed** 2020-05-22 06:29 UTC
