### ISSUE TITLE
Support fror s3a hadoop file system is broken

### ISSUE THREAD

**Issue by robertfirek** [pinterest/secor#153] opened 2015-12-11 16:59 UTC
I've tried use s3a file system in my configuration, but I've get error:

```
java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key 
must be specified as the username or password (respectively) of a s3n URL, 
or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey 
properties (respectively).
```

After short investigation I've noticed that support for s3a introduced in commit  [Support s3a hadoop file system.](https://github.com/pinterest/secor/commit/e00fac6be98d8dda0739f591ab429a8584d85b78) was accidentally destroyed by next commit [Openstack Swift integration](https://github.com/pinterest/secor/commit/049379a6168eb56c688b387896bb4462aa2e76e1).

In the class **com.pinterest.secor.uploaderHadoopS3Uploader** the method **mConfig.getS3Prefix()** was replaced with **com.pinterest.secor.util.FileUtil.getPrefix()** which doesn't support "s3a". Probably only change which have to be made to restore s3a support is change in the **com.pinterest.secor.util.FileUtil.getPrefix()** method. 

Line 90:

```
prefix = "s3n://" + config.getS3Bucket() + "/" + config.getS3Path();
```

should be changed to:

```
prefix = config.getS3Prefix();
```

**Comment by HenryCaiHaiying** [comment] 2015-12-11 19:02
Good catch.  Can you prepare a PR for this fix?

**Comment by robertfirek** [comment] 2015-12-12 15:28
@HenryCaiHaiying Done (Restore support for s3a file system)[https://github.com/pinterest/secor/pull/155]

**Comment by robertfirek** [comment] 2015-12-14 10:38
@HenryCaiHaiying When do you plan to release the new version with this change?

**Comment by HenryCaiHaiying** [comment] 2015-12-14 18:22
Do you want me to cut a new maven version with this change?

**Comment by robertfirek** [comment] 2015-12-14 21:55
In our project we use Jar file from the maven repository. If you can release new version to the maven repository I can avoid creating my own distribution.

**Comment by HenryCaiHaiying** [comment] 2015-12-14 23:12
I cut 0.9 version, it should show up in maven central after one hour.

**Comment by robertfirek** [comment] 2015-12-15 10:40
@HenryCaiHaiying Thank you

**Comment by dzlab** [comment] 2016-02-05 10:48
why this issue is still open? has the fixe not been yet merged?? I'm trying to use s3a (to avoid putting AWS credentials in the properties file and instead use AMI instance role).

**Comment by HenryCaiHaiying** [comment] 2016-02-05 23:52
Which version of secor are you using?  We don't use s3a here, but according
to Robert, the problem is already fixed.

**Comment by dzlab** [comment] 2016-02-06 12:52
@HenryCaiHaiying I was using the latest version with s3a, but when I noticed this issue I thought the support is broken which is not the case. 
Now, my problem is [No broker partions consumed by consumer thread secor_backup_X for topic Y](https://groups.google.com/forum/#!topic/secor-users/I4EvfRqem8s), And Secor is not archiving in S3. Any hint to fix that?

**Closed** 2017-03-16 23:04 UTC
