### ISSUE TITLE
Secor is leaking memory through DeleteOnExit

### ISSUE THREAD

**Issue by giner** [pinterest/secor#785] opened 2019-06-18 02:36 UTC
Secor is exhausting the while heap over time and either crashes or starts spinning due to GC trying to free memory very frequently. Memory is accumulated in the **DeleteOnExitHook** by **DeleteOnExit** method. We are running Secor v0.25 and the related code seems to be the same in the latest version (which is v0.27 at the moment of writing).

![secor - memory usage over time](https://user-images.githubusercontent.com/533434/59649270-02015900-91bd-11e9-8a65-286b3c73add5.png)
![secor - memory dump analysis 1](https://user-images.githubusercontent.com/533434/59649276-07f73a00-91bd-11e9-8e51-d6a2a04d9b82.png)
![secor - memory dump analysis 2](https://user-images.githubusercontent.com/533434/59649280-0f1e4800-91bd-11e9-8f42-cf812c7002cb.png)

**Comment by dovka** [comment] 2019-10-02 07:43
We are getting the same problem - every few days secor crashes with identical Memory and CPu patterns. Filed under #964

**Comment by yehoshoua** [comment] 2020-05-17 13:33
any updates ?

**Comment by HenryCaiHaiying** [comment] 2020-05-18 01:41
This is interesting.  If you can reproduce the problem, can you turn on the debug logging category for FileRegistry.java which will prints out all the files added for deleteOnExit.

It would be interesting to see why there will be so many files added, we have never seen the memory problem on DeleteOnExitHook before and DeleteOnExitHook doesn't have a method to clear the map either.  One suspicion I have is the file size is set to too small (secor.max.file.size.bytes and secor.max.file.age.seconds) so it ends up creating too many files.

**Comment by pdambrauskas** [comment] 2020-07-07 15:26
I think I have the same problem. 
In my case, I have custom `MessageParser` implementation, which adds multi-level partitions, something like: `/owner=1/workspace=2/event=click/dt=2020-07-07` in that case, we can get really big number of files and storing them in compressed parquet ads up to even biger memory consumption.

Any ideas on how to approach this problem?
Maybe we should pause Kafka consumers, when we reach X number of files, upload those files and resume? But in that case we'll potentially have many small files :thinking:.  We could also partition kafka topic by same values as we partition our data on  destination system, in that case consumed data would appear on same consumer thread and that would help us to have smaller number of files?

**Comment by HenryCaiHaiying** [comment] 2020-07-08 19:09
Looks good to me, I left a small comment in the code for backward compatible behavior.   And I don't think we should sort the files since that would change the file uploading order, some people might not like that.

**Comment by HenryCaiHaiying** [comment] 2020-07-09 18:55
@giner @dovka @yehoshoua Do you guys want to try https://github.com/pinterest/secor/pull/1443?

**Comment by dovka** [comment] 2020-07-09 20:43
Thank you Henry.
is #1443 parameter going to limit the throughout?

Which release it will be available?

**Comment by HenryCaiHaiying** [comment] 2020-07-09 21:48
I haven't cut any release yet since this PR is just landed.  I think you can just pull that PR's classes into your local build to try it out, it's a very simple PR.   I don't think it will affect the upload throughput since most of your files are probably small files and you can tune the upload threshold parameter.

**Comment by giner** [comment] 2020-07-10 04:27
I'm wondering why using deleteOnExit at all? It could be fine if there was a limited number of files created during the process lifetime hover it's not the case with Secor and deleteOnExit doesn't release memory until the process is restarted.

**Comment by pdambrauskas** [comment] 2020-07-10 07:35
Yes, my change solves only one part of the problem, it helps to keep `FileRegistry` HashMaps sizes under controll:
```
private HashMap<TopicPartitionGroup, HashSet<LogFilePath>> mFiles;
private HashMap<LogFilePath, FileWriter> mWriters;
private HashMap<LogFilePath, Long> mCreationTimes;
```
that was enough for me, to keep secor running without OOM for now.

It does not affect DeleteFileOnExit though.
It would be nice to use FileRegistry on the hook, so we have single list of active files, but since the hook is `static`, we cannot access that list :(.

What is the idea behind DeleteOnExit tracking list of files? Wouldn't it be sufficient to delete all staged files on exit?

**Closed** 2020-07-11 23:17 UTC
